#GitHub action is a infile storing and fetching data technique in this we use 
#upload and Download artfifacts as an action parameters

name: Github artifacts

on:
    workflow_dispatch:

jobs:
    job_1:
        name: Uploading artifact

        runs-on: ubuntu-latest

        steps:

         - name: "Create a local file" 
           run: |
                  echo "I am storing this file as workflow artifact" > file.txt
         - uses: action/upload-artifact@v2
           with:
                    name: file
                    path: file.txt
    job_2:
        name: Downloading artifact

        runs-on: ubuntu-latest

        needs: job_1
        steps:
            - name: "Downloading artifact"
              uses: action/download-artifact@v2
              with: 
                name: file
              run: cat file.txt


                  
