name: "Environment test"

on:
  workflow_dispatch:
#This is Global environmnet variable section
env:
  value1: bimal
  value2: Khimdung

jobs:
  testjob:
    name: "testing evnironment variable"

    runs-on: ubuntu-latest
    #This is Local environment variable section
    env:
      value_local1: Hi
      value_local2: how are you?

    steps:
      - name: printing values of variable
        run: |
          echo "${{env.value_local1}} ${{env.value1}} ${{env.value2}} ${{env.value_local2}}"

 Default-env:
    name: Checking default variable
    runs-on: ubuntu-latest
    steps:
     run: |
        echo "${{env.GITHUB_RUN_NUMBER}}""
