name: Github secret

on: 
    workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest
        steps:
         - name: fetching secret from github
           run: |
            echo "AWS secrect key is: ${{secrets.AWS_ACESS_KEY}}"
        env: 
            aws-acess-key: ${{secrets.AWS_ACESS_KEY}}
            run: |
              echo "Acessing through Variable ${{secrets.AWS_ACESS_KEY}}" 
